### PR TITLE
removed blank lines and put the .so in th correct folder

### PR DESCRIPTION
**Pull request by AndreasHeine**

### CODE REVIEW

**Comment by AndreasHeine** [comment]
my Dockerfile:
```
FROM node:14.10.1-buster
LABEL maintainer="Instinct-Gaming altv:RP"

WORKDIR /altv

ARG BRANCH=release

ENV PORT 7788

RUN apt-get update && \
    apt-get install -y wget libc-bin libatomic1

RUN mkdir /altv/data && \
    mkdir /altv/resources-data && \
    mkdir -p /altv/modules/js-module && \
    wget --no-cache -O /altv/altv-server https://cdn.altv.mp/server/${BRANCH}/x64_linux/altv-server && \
    wget --no-cache -O /altv/data/vehmodels.bin https://cdn.altv.mp/server/${BRANCH}/x64_linux/data/vehmodels.bin && \
    wget --no-cache -O /altv/data/vehmods.bin https://cdn.altv.mp/server/${BRANCH}/x64_linux/data/vehmods.bin && \
    wget --no-cache -O /altv/modules/js-module/libjs-module.so https://cdn.altv.mp/js-module/${BRANCH}/x64_linux/modules/js-module/libjs-module.so && \
    wget --no-cache -O /altv/modules/js-module/libnode.so.72 https://cdn.altv.mp/js-module/${BRANCH}/x64_linux/modules/js-module/libnode.so.72

RUN apt-get purge -y wget && \
    apt-get clean

RUN mkdir /altv-persistend && \
    mkdir /altv-persistend/config && \
    mkdir /altv-persistend/resources && \
    mkdir /altv-persistend/logs && \
    mkdir /altv-persistend/resources-data && \
    ln -s /altv-persistend/config /altv/config && \
    ln -s /altv-persistend/resources /altv/resources && \
    ln -s /altv-persistend/resources-data /altv/resources-data && \
    ln -s /altv-persistend/logs /altv/logs

EXPOSE ${PORT}/tcp
EXPOSE ${PORT}/udp

EXPOSE 7790

VOLUME /altv-persistend/

ADD resources/. /altv/resources
ADD config.json /altv/config
ADD server.cfg /altv
ADD package.json /altv

RUN npm install

ADD start.sh /altv/start.sh
RUN chmod +x /altv/start.sh
RUN chmod +x /altv/altv-server

# Start AltV Server
USER 0
ENTRYPOINT ["/altv/start.sh"]
CMD ["bash"]
```

"docker build . -t altv"  
"docker run -d -p 7788:7788 -p 7788:7788/udp -p 7790:7790 -p 17888:17888 --name altV-RP altv"   
or
"docker run -it -p 7788:7788 -p 7788:7788/udp -p 7790:7790 -p 17888:17888 --name altV-RP altv"

**Comment by ThomasMarangoni** [comment]
I don't like to fix the space, because I want to visually seperate server and modules, because I also maintaine a csharp version and it's easier to maintain then.

**Comment by ThomasMarangoni** [comment]
I fixed the path error

**Comment by AndreasHeine** [comment]
> I don't like to fix the space, because I want to visually seperate server and modules, because I also maintaine a csharp version and it's easier to maintain then.

then the dockerfile is unusable! result is a crash on build...
Unbenannt

you would need a additional "RUN" for each blank line...

**Comment by ThomasMarangoni** [comment]
for me it runs without problems, I think I need to investigate further, how do you run the file?

**Comment by AndreasHeine** [comment]
see above! And Visual Studio Code also marks it as wrong syntax!

**Comment by AndreasHeine** [comment]
[WARNING]: Empty continuation line found in:
    RUN mkdir /altv &&     mkdir /altv/data &&     mkdir /altv/resources-data &&     mkdir -p /altv/modules/js-module &&     wget --no-cache -O /altv/altv-server https://cdn.altv.mp/server/${BRANCH}/x64_linux/altv-server &&     wget --no-cache -O /altv/data/vehmodels.bin https://cdn.altv.mp/server/${BRANCH}/x64_linux/data/vehmodels.bin &&     wget --no-cache -O /altv/data/vehmods.bin https://cdn.altv.mp/server/${BRANCH}/x64_linux/data/vehmods.bin &&     wget --no-cache -O /altv/modules/js-module/libjs-module.so https://cdn.altv.mp/js-module/${BRANCH}/x64_linux/modules/js-module/libjs-module.so &&     wget --no-cache -O /altv/modules/js-module/libnode.so.72 https://cdn.altv.mp/js-module/${BRANCH}/x64_linux/modules/js-module/libnode.so.72
[WARNING]: Empty continuation lines will become errors in a future release.

**Comment by ThomasMarangoni** [comment]
Fixed Warning with last commit

**Pull request closed without merging**
